apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: sample
spec:
  storageClassName: ibmc-vpc-block-10iops-tier
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
